global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'streamlit'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['streamlit:8501']




# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

#   - job_name: 'airflow'
#     static_configs:
#       - targets: ['airflow-webserver:8080']
  
#   - job_name: 'streamlit'
#     metrics_path: '/metrics'
#     static_configs:
#       - targets: ['streamlit:8501']
  
#   - job_name: 'locust'
#     static_configs:
#       - targets: ['locust:8089']
#     metrics_path: '/metrics'

#   - job_name: 'mlflow'
#     static_configs:
#       - targets: ['mlflow:5000']

  ### Previous versions:

# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["localhost:9090"]

#   - job_name: "airflow"
#     static_configs:
#       - targets: ["airflow-webserver:8080"]
      
  ###

#   global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["localhost:9090"]

#   - job_name: "airflow"
#     static_configs:
#       - targets: ["airflow-webserver:8080"]

#   - job_name: "mlflow"
#     static_configs:
#       - targets: ["mlflow:5000"]
